name: MariaDB Test

on: [push]

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb
          env:
            MYSQL_ROOT_PASSWORD: root
          ports:
            - 3306
          options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Setup DB
        run: |
          sudo apt install -y mysql-client
          mysql --host 127.0.0.1 --port ${{ job.services.mariadb.ports[3306] }} -uroot -proot -e "SHOW GRANTS FOR root@localhost"